export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const RESTORE_BASKET_FROM_LOCAL_STORAGE = 'RESTORE_BASKET_FROM_LOCAL_STORAGE';
export const SET_TO_BASKET_PRODUCT_COUNT = 'SET_TO_BASKET_PRODUCT_COUNT';